version: 0.2
env:
    variables:
        SolutionFilePath: "./POC.CP.WebApi.sln"
        ProjectFilePath: "./POC.CP.WebApi/POC.CP.WebApi.csproj"
        Configuration: "Release"
        PublishDir: "Publish_Output"
phases:
    install:
      runtime-versions:
        docker: 18
        dotnet: 2.2
    pre_build:
        commands:
            - echo Restore started on `date`
            - dotnet restore $ProjectFilePath
    build:
        commands:
            - echo Build started on `date`
            - dotnet publish $ProjectFilePath -c $Configuration -o $CODEBUILD_SRC_DIR/$PublishDir
            - ls ./$PublishDir
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - "**/*"
    base-directory: "$PublishDir"